/**
 * 地址操作
 */
export const RECEIVE_ADDRESSLIST = 'RECEIVE_ADDRESSLIST'
export const ADD_TO_ADDRESS = 'ADD_TO_ADDRESS'
export const EDIT_TO_ADDRESS = 'EDIT_TO_ADDRESS'
export const SET_DEFAULT_ADDR = 'SET_DEFAULT_ADDR'
export const DEL_TO_ADDRESS = 'DEL_TO_ADDRESS'

/**
 * 首页
 */

export const RECEIVE_BANNERS = 'RECEIVE_BANNERS'
export const RECEIVE_ACTIVITY = 'RECEIVE_ACTIVITY'
export const RECEIVE_COLUMNS = 'RECEIVE_COLUMNS'
export const RECEIVE_INTEGRAL_BANNERS = 'RECEIVE_INTEGRAL_BANNERS'
export const RECEIVE_INTEGRAL_COLUMNS = 'RECEIVE_INTEGRAL_COLUMNS'
export const RECEIVE_FLEAMARKET_BANNERS = "RECEIVE_FLEAMARKET_BANNERS"
export const RECEIVE_FLEAMARKET_SALE_COLUMNS = "RECEIVE_FLEAMARKET_SALE_COLUMNS"
export const RECEIVE_FLEAMARKET_BUY_COLUMNS = "RECEIVE_FLEAMARKET_BUY_COLUMNS"

/**
 * 分类
 */
export const RECEIVE_CATEGORY = 'RECEIVE_CATEGORY'
export const RECEIVE_JIFEN_CATEGORY = 'RECEIVE_JIFEN_CATEGORY'


/**
 * 商品
 */

export const RECEIVE_GOODS = 'RECEIVE_GOODS'
export const RECEIVE_JFGOODS = 'RECEIVE_JFGOODS'
